name: Deploy Virtual Economy Framework
run-name: ${{ github.repository }} automated deployment ğŸš€
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by ${{ github.actor }} through a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by the VEF Community"
      - run: echo "ğŸ” Branch to be deployed... ${{ github.ref }}"
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Run the docker-compose file to start the (container) services
        run: |
          docker-compose -f docker-compose.yml up -d
      - name: Check the (container) services
        run: |
          docker container ls
      - name: Check the IP
        run: |
          ip address
      - run: echo "ğŸ This job's status is ${{ job.status }}."
